name: notification_app
description: "A Flutter project to notify users to call contacts after 3 months."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # 1. እውቂያዎችን ከስልክ ላይ ለማንበብ
  flutter_contacts: ^1.1.9+1
  
  # 2. ማሳወቂያ (Notification) ለተጠቃሚው ለመላክ
  flutter_local_notifications: ^17.0.0
  
  # 3. አፑ በተዘጋበት ሰዓትም በጀርባ ሆኖ ሥራውን እንዲሠራ (Background Service)
  workmanager: ^0.5.2
  
  # 4. የስልኩን መረጃዎች (ለምሳሌ የመጨረሻ የጥሪ ሰዓት) ለጊዜው መዝግቦ ለመያዝ
  shared_preferences: ^2.2.2
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true